FROM ros:indigo-ros-core
RUN apt-get -y update
RUN sudo apt-get install -y ros-indigo-turtlebot-simulator
RUN sudo apt-get install -y ros-indigo-turtlebot-apps ros-indigo-turtlebot-rviz-launchers
CMD /ros_entrypoint.sh bash
